import i1 from '../images/travis.png';
import i2 from '../images/bogo.jpg';
import i3 from '../images/bogo.jpg';
import i4 from '../images/bogo.jpg';
import i5 from '../images/off.jpg';

const data = {
products: [
    {id: 1,
    img: i1,
    brand: "Nike",
    model: "Dunk Low Travis Scott",
    date: "11.05.2021",
    price: "120$"},
    {id: 2,
    img: i2,
    brand: "Nike",
    model: "Air Jordan 4",
    date: "14.05.2021",
    price: "250$"},
    {id: 3,
    img: i3,
    brand: "Adidas",
    model: "Yeezy Boost 350v2",
    date: "17.05.2021",
    price: "200$"},
    {id: 4,
    img: i4,
    brand: "Supreme",
    model: "Box Logo Hoodie",
    date: "22.05.2021",
    price: "180$"},
    {id: 5,
    img: i5,
    brand: "Nike",
    model: "Air Force 1 Off White",
    date: "29.05.2021",
    price: "220$"},
    {id: 6,
        img: i1,
        brand: "Nike",
        model: "Dunk Low Travis Scott",
        date: "11.05.2021",
        price: "120$"},
        {id: 7,
        img: i2,
        brand: "Nike",
        model: "Air Jordan 4",
        date: "14.05.2021",
        price: "250$"},
        {id: 8,
        img: i3,
        brand: "Adidas",
        model: "Yeezy Boost 350v2",
        date: "17.05.2021",
        price: "200$"},
        {id: 9,
        img: i4,
        brand: "Supreme",
        model: "Box Logo Hoodie",
        date: "22.05.2021",
        price: "180$"},
        {id: 10,
        img: i5,
        brand: "Nike",
        model: "Air Force 1 Off White",
        date: "29.05.2021",
        price: "220$"},
        {id: 11,
            img: i1,
            brand: "Nike",
            model: "Dunk Low Travis Scott",
            date: "11.05.2021",
            price: "120$"},
            {id: 12,
            img: i2,
            brand: "Nike",
            model: "Air Jordan 4",
            date: "14.05.2021",
            price: "250$"},
            {id: 13,
            img: i3,
            brand: "Adidas",
            model: "Yeezy Boost 350v2",
            date: "17.05.2021",
            price: "200$"},
            {id: 14,
            img: i4,
            brand: "Supreme",
            model: "Box Logo Hoodie",
            date: "22.05.2021",
            price: "180$"},
            {id: 15,
            img: i5,
            brand: "Nike",
            model: "Air Force 1 Off White",
            date: "29.05.2021",
            price: "220$"},
            {id: 16,
                img: i1,
                brand: "Nike",
                model: "Dunk Low Travis Scott",
                date: "11.05.2021",
                price: "120$"},
                {id: 17,
                img: i2,
                brand: "Nike",
                model: "Air Jordan 4",
                date: "14.05.2021",
                price: "250$"},
                {id: 18,
                img: i3,
                brand: "Adidas",
                model: "Yeezy Boost 350v2",
                date: "17.05.2021",
                price: "200$"},
]
};

export default data;